#############################################################################
## Server configuration
#############################################################################
server:
  port: ${PORT:8080}
#############################################################################
## Log configuration
#############################################################################
logging:
  level:
    root: INFO
#############################################################################
## Messages configuration
#############################################################################
spring:
  messages:
    always-use-message-format: true
    basename: i18n/messages
    encoding: UTF-8

#############################################################################
## Actuator EndPoints configuration
#############################################################################
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
  monitors:
    enabled: true
