#############################################################################
## Server configuration
#############################################################################
server:
  port: ${PORT:9075}

#############################################################################
## Database Configuration
#############################################################################
